# Generated by Django 3.2.10 on 2021-12-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211223_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='path',
        ),
    ]
