# Generated by Django 3.2.10 on 2021-12-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_datamodel_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='path',
            field=models.TextField(default='empty'),
        ),
    ]
