# Generated by Django 3.2.10 on 2021-12-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_datamodel_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='target_variable',
            field=models.TextField(default='empty'),
        ),
    ]
